api/app/Models/Project/Project.php

Update Project MoneyBudget value

---

api/app/Http/Controllers/BaseController.php
api/app/Http/Controllers/api/v1/ProjectController.php
frontend/src/form/fields/timetrack/TimeEffortValueField.tsx
frontend/src/views/timetrack/TimetrackFormDialog.tsx

fixed the conversion between rates when modiying the project effort

merge rate conversion fixes

---

frontend/src/form/fields/Select.tsx

truncate chips with a long text so that it doesn't overlap with other input forms which might be adjacent.

fix chips which overlap with other input

---

frontend/src/layout/OverviewTable.tsx
frontend/src/stores/abstractCachedStore.ts
frontend/src/stores/abstractPaginatedStore.ts
frontend/src/stores/abstractStore.ts
frontend/src/stores/companyStore.ts
frontend/src/stores/employeeStore.ts
frontend/src/stores/invoiceStore.ts
frontend/src/stores/offerStore.ts
frontend/src/stores/peopleStore.ts
frontend/src/stores/projectStore.ts
frontend/src/types.ts
frontend/src/utilities/Cache.ts

Made paginated stores cached by adding a local cache. The cache is fairly simple for now. Improvements will come as needed.

introduce local cache to get rid of redundant queries

---

apir/app/controllers/v2/holidays_controller.rb
apir/app/decorators/holiday_decorator.rb
apir/app/views/v2/holidays/index.json.jbuilder
apir/app/views/v2/holidays/show.json.jbuilder
apir/config/routes.rb
apir/db/migrate/20200121134534_customer_compatibility.rb
apir/spec/controllers/holidays_controller_spec.rb
apir/spec/decorators/holiday_decorator_spec.rb
frontend/src/stores/holidayStore.ts

Add the holidays to the ruby backend (create, update, destroy, duplicate and index)

add holiday controller

---

apir/app/controllers/v2/companies_controller.rb
apir/app/views/v2/companies/index.json.jbuilder
apir/app/views/v2/companies/show.json.jbuilder
apir/app/views/v2/customers/index.json.jbuilder
apir/app/views/v2/customers/index.xlsx.axlsx
apir/app/views/v2/customers/show.json.jbuilder
apir/app/views/v2/customers_import/verify.json.jbuilder
apir/db/migrate/20190513131923_create_customers.rb
apir/db/schema.rb
apir/spec/factories/customers.rb
frontend/src/views/persons/PersonForm.tsx

334 Finished

---

apir/app/controllers/v2/companies_controller.rb
apir/app/controllers/v2/people_controller.rb
apir/app/views/v2/companies/index.json.jbuilder
apir/app/views/v2/companies/show.json.jbuilder
apir/app/views/v2/customers/index.json.jbuilder
apir/app/views/v2/customers/show.json.jbuilder
apir/app/views/v2/customers_import/verify.json.jbuilder
apir/app/views/v2/people/index.json.jbuilder
apir/app/views/v2/people/show.json.jbuilder
apir/db/migrate/20190513131923_create_customers.rb
apir/db/schema.rb
apir/spec/factories/customers.rb
frontend/src/types.ts
frontend/src/views/companies/CompanyCreate.tsx
frontend/src/views/persons/PersonCreate.tsx

Live um die Datenbankänderungen zurück zuschalten.

code clean up

---

frontend/src/form/entitySelect/EmployeeSelect.tsx
frontend/src/form/entitySelect/ProjectCommentPresetSelect.tsx
frontend/src/form/entitySelect/ProjectSelect.tsx
frontend/src/form/entitySelect/ServiceSelect.tsx
frontend/src/form/fields/Select.tsx

Projects sorted chronologically by updated_by and fixed the Select Menu not being visible due to being off screen.

Projects sorted chronologically

---

.gitignore
apir/Gemfile.lock
apir/app/controllers/v2/project_comments_controller.rb
apir/app/controllers/v2/project_efforts_controller.rb
apir/app/services/comment_mover.rb
apir/config/locales/de.yml
apir/config/routes.rb
frontend/src/form/fields/timetrack/EffortValueField.tsx
frontend/src/index.css
frontend/src/layout/OverviewTable.tsx
frontend/src/stores/effortStore.ts
frontend/src/stores/offerStore.ts
frontend/src/stores/projectCommentPresetStore.ts
frontend/src/stores/projectCommentStore.ts
frontend/src/stores/timetrackFilterStore.ts
frontend/src/types.ts
frontend/src/views/projects/ProjectPositionRenderer.tsx
frontend/src/views/timetrack/EffortMoveDialog.tsx
frontend/src/views/timetrack/Timetrack.tsx
frontend/src/views/timetrack/TimetrackEmployeeGroup.tsx
frontend/src/views/timetrack/TimetrackEntityGroup.tsx
frontend/src/views/timetrack/TimetrackExpansionPanel.tsx
frontend/src/views/timetrack/TimetrackFormDialog.tsx
frontend/src/views/timetrack/TimetrackProjectCombinedTable.tsx
frontend/src/views/timetrack/TimetrackProjectGroup.tsx
frontend/src/views/timetrack/TimetrackProjectSoloTable.tsx
frontend/src/views/timetrack/TimetrackProjectTable.tsx
frontend/src/views/timetrack/TimetrackServiceGroup.tsx

Refined project comments. Also removed ambiguity of "effort" in german (Leistung => Aufwand).

Added ability to move project comments

---

frontend/src/layout/Overview.tsx
frontend/src/layout/icons.tsx
frontend/src/stores/abstractStore.ts
frontend/src/stores/peopleStore.ts
frontend/src/types.ts
frontend/src/views/persons/PersonOverview.tsx

One can now select multiple clients and copy their e-mail addresses with one click.

Copy e-mails from selected clients

---

frontend/src/views/persons/PersonOverview.tsx

Now it also exports the selected clients email addresses directly into the default mail client.

Export clients email to mail client

---

apir/Gemfile.lock
apir/app/controllers/v2/project_categories_controller.rb
apir/app/models/address.rb
apir/app/models/customer.rb
apir/app/models/phone.rb
apir/app/views/v2/companies/index.json.jbuilder
apir/app/views/v2/companies/show.json.jbuilder
apir/app/views/v2/customer_tags/index.json.jbuilder
apir/app/views/v2/customer_tags/show.json.jbuilder
apir/app/views/v2/customers/index.json.jbuilder
apir/app/views/v2/customers/show.json.jbuilder
apir/app/views/v2/customers_import/verify.json.jbuilder
apir/app/views/v2/employee_groups/index.json.jbuilder
apir/app/views/v2/employee_groups/show.json.jbuilder
apir/app/views/v2/employees/index.json.jbuilder
apir/app/views/v2/employees/show.json.jbuilder
apir/app/views/v2/people/index.json.jbuilder
apir/app/views/v2/people/show.json.jbuilder
apir/app/views/v2/project_categories/index.json.jbuilder
apir/app/views/v2/project_categories/show.json.jbuilder
apir/db/migrate/20200526082727_add_hidden_to_address.rb
apir/db/migrate/20200526122928_add_addresses_to_employees.rb
apir/db/migrate/20200625102546_employee_first_vactaion_takeover_default.rb
apir/db/migrate/20210514064853_employee_archived_default.rb
apir/db/migrate/20210514105125_work_period_hourly_paid_default.rb
apir/db/schema.rb
apir/db/seeds.rb

#364 Test pull to check if migrations work on dev db

364-railsDB-update

---

apir/Gemfile.lock
apir/app/controllers/v2/reports_controller.rb
apir/app/services/cost_breakdown.rb
apir/app/services/pdfs/effort_report_pdf.rb
apir/app/services/pdfs/generators/breakdown_table_generator.rb
apir/app/services/pdfs/generators/mail_header_generator.rb
apir/app/services/pdfs/project_report_pdf.rb
apir/config/locales/de.yml
apir/config/locales/fr.yml
frontend/src/views/reports/ProjectReport.tsx

The project report has been updated, both the layout and the content. Also, a divide by 0 bug has been fixed in the cost_breakdown that resulted in some errors with invoices.

Project Report

---

apir/app/controllers/v2/invoices_controller.rb
apir/app/controllers/v2/offers_controller.rb
frontend/src/form/fields/DatePicker.tsx
frontend/src/form/fields/timetrack/DateFastPicker.tsx
frontend/src/utilities/formatter.ts
frontend/src/utilities/momentUtcUtils.ts

make DatePicker use the UTC timezone.

---

frontend/src/views/timetrack/TimetrackEmployeeGroup.tsx

fix frontend crash if date text field is empty.

---

frontend/src/form/FormikSubmitDetector.tsx
frontend/src/form/fields/formik.tsx
frontend/src/layout/ActionButton.tsx
frontend/src/layout/ConfirmationDialog.tsx
frontend/src/views/invoices/InvoiceForm.tsx

435 invoice date change

---

apir/db/migrate/20211007100147_replace_floats_by_decimals.rb
apir/db/schema.rb
apir/spec/controllers/services_controller_spec.rb
apir/spec/other/cost_breakdown_spec.rb
apir/spec/other/project_calculator_spec.rb
apir/spec/other/rate_unit_updater_spec.rb

Make ruby DB schema match what's actually in the SQL db.

---

apir/app/models/project_position.rb

allow deletion of project_position even if it has invoice_positions.

---

frontend/src/views/invoices/DraggableTableBody.tsx

fix drag-n-drop warning.

---

apir/app/controllers/v2/companies_controller.rb
apir/app/controllers/v2/people_controller.rb
apir/app/models/customer.rb
apir/app/views/v2/companies/index.json.jbuilder
apir/app/views/v2/companies/show.json.jbuilder
apir/app/views/v2/customers/index.json.jbuilder
apir/app/views/v2/customers/show.json.jbuilder
apir/app/views/v2/people/index.json.jbuilder
apir/app/views/v2/people/show.json.jbuilder
apir/db/migrate/20211122092713_make_customers_archivable.rb
apir/db/schema.rb
frontend/src/stores/companyStore.ts
frontend/src/stores/peopleStore.ts
frontend/src/types.ts
frontend/src/views/companies/CompanyCreate.tsx
frontend/src/views/companies/CompanyForm.tsx
frontend/src/views/companies/CompanyOverview.tsx
frontend/src/views/persons/PersonCreate.tsx
frontend/src/views/persons/PersonForm.tsx
frontend/src/views/persons/PersonOverview.tsx

474 archive customers

---

frontend/src/views/companies/companySchema.ts
frontend/src/views/persons/personSchema.ts

require customers to have at least one tag.

---

frontend/src/form/entitySelect/EmployeeSelect.tsx

put regular employees above zivis.

---

apir/app/controllers/v2/invoices_controller.rb
apir/app/services/pdfs/invoice_qr_bill_pdf.rb

make qr-bill filename use current date.

---

frontend/src/form/FormView.tsx
frontend/src/views/invoices/InvoiceForm.tsx
frontend/src/views/offers/OfferForm.tsx
frontend/src/views/projects/ProjectForm.tsx

force offer to be saved before creating a project.

---

apir/app/views/v2/companies/show.json.jbuilder

don't include duplicate company data.

---

frontend/src/stores/companyStore.ts
frontend/src/stores/costgroupStore.ts
frontend/src/stores/customerStore.ts
frontend/src/stores/customerTagStore.ts
frontend/src/stores/effortStore.ts
frontend/src/stores/employeeGroupStore.ts
frontend/src/stores/employeeStore.ts
frontend/src/stores/globalSettingStore.ts
frontend/src/stores/holidayStore.ts
frontend/src/stores/invoiceStore.ts
frontend/src/stores/offerStore.ts
frontend/src/stores/peopleStore.ts
frontend/src/stores/positionGroupStore.ts
frontend/src/stores/projectCategoryStore.ts
frontend/src/stores/projectCommentPresetStore.ts
frontend/src/stores/projectCommentStore.ts
frontend/src/stores/projectStore.ts
frontend/src/stores/projectWithPotentialInvoicesStore.ts
frontend/src/stores/rateGroupStore.ts
frontend/src/stores/rateUnitStore.ts
frontend/src/stores/serviceStore.ts
frontend/src/utilities/Cache.ts
frontend/src/utilities/notifier.ts

Fix an issue where saving a project / invoice / etc. would't show the saving / done message.

470 fix save status

---

frontend/src/views/offers/OfferForm.tsx
frontend/src/views/offers/OfferPositionRenderer.tsx

499 lock offer

---

frontend/src/form/dialog/CitySelectDialog.tsx
frontend/src/layout/PrintButton.tsx
frontend/src/layout/UnstyledBackendLink.tsx
frontend/src/layout/UnstyledLink.tsx

Remove various style hacks and use MUI theme functionality instead.

fix styling.

---

apir/app/services/pdfs/invoice_qr_bill_pdf.rb

tweak QR bill layout.

---

apir/Gemfile.lock
frontend/src/form/fields/common.tsx
frontend/src/locales/messages.de.json
frontend/src/locales/messages.fr.json
frontend/src/utilities/validation.ts
frontend/src/utilities/wrapIntl.ts
frontend/src/views/companies/companySchema.ts
frontend/src/views/employees/employeeSchema.tsx
frontend/src/views/invoices/invoiceSchema.tsx
frontend/src/views/offers/offerSchema.tsx
frontend/src/views/persons/personSchema.ts
frontend/src/views/projects/projectSchema.tsx
frontend/src/views/timetrack/EffortMoveDialog.tsx
frontend/src/views/timetrack/TimetrackFormDialog.tsx

222 localize yup

---

apir/app/services/revenue_report_service.rb

include offer status in revenue report.

---

frontend/src/form/fields/DatePicker.tsx
frontend/src/views/employees/WorkPeriodSubform.tsx

make DatePicker not cover the year of the work period.

---

apir/app/controllers/v2/service_cost_reports_controller.rb
apir/app/services/project_service_cost_report_service.rb
apir/app/services/project_service_hour_report_service.rb
apir/app/views/v2/service_cost_reports/project.xlsx.axlsx
apir/config/routes.rb
frontend/src/App.tsx
frontend/src/form/fields/Select.tsx
frontend/src/layout/Navigation.tsx
frontend/src/layout/Snackbar.tsx
frontend/src/locales/messages.de.json
frontend/src/locales/messages.fr.json
frontend/src/views/reports/ServiceCostReports.tsx
frontend/src/views/reports/ServiceHourReports.tsx

Create a new report that lists money grouped by project and service.

551 service cost report

---

docker-compose.yml
frontend/src/form/dialog/ServiceSelectDialog.tsx
frontend/src/form/fields/Select.tsx
frontend/src/views/services/ServiceForm.tsx
frontend/src/views/services/serviceSchema.tsx

Fix two minor issues from 549.
Update to node 12.

549 minor fixes & update node.

---

apir/app/services/pdfs/invoice_qr_bill_pdf.rb

Fix qr code input

---

apir/app/services/pdfs/effort_report_pdf.rb

* Merge Develop (#596)
* Update README.md (#593)
* #594 Fix Service Form (#595)
* #594 Fix Service Form
* Fixed comment
* Merge (#598)
* Update README.md (#593)
* #594 Fix Service Form (#595)
* #594 Fix Service Form
* Fixed comment
* Fixed pdf error (#597)
* Merge (#604)
* Update README.md (#593)
* #594 Fix Service Form (#595)
* #594 Fix Service Form
* Fixed comment
* Fixed pdf error (#597)
* Added percentages when there are multiple project_categories (#603)
* Merge (#606)
* Update README.md (#593)
* #594 Fix Service Form (#595)
* #594 Fix Service Form
* Fixed comment
* Fixed pdf error (#597)
* Added percentages when there are multiple project_categories (#603)
* Project service hour report improvement project categories (#605)
* Added percentages when there are multiple …

Fix invoice position description (#646)
